# Generated by Django 5.2.4 on 2025-07-09 01:30

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do produto (máximo 200 caracteres)', max_length=200, verbose_name='Nome do Produto')),
                ('descricao', models.TextField(help_text='Descrição detalhada do produto', verbose_name='Descrição')),
                ('preco', models.DecimalField(decimal_places=2, help_text='Preço do produto em reais', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Preço')),
                ('categoria', models.CharField(choices=[('Eletrônicos', 'Eletrônicos'), ('Informática', 'Informática'), ('Áudio', 'Áudio'), ('Casa e Jardim', 'Casa e Jardim'), ('Esportes', 'Esportes'), ('Moda', 'Moda'), ('Livros', 'Livros')], help_text='Categoria do produto', max_length=50, verbose_name='Categoria')),
                ('estoque', models.PositiveIntegerField(default=0, help_text='Quantidade em estoque', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Estoque')),
                ('ativo', models.BooleanField(default=True, help_text='Produto ativo/visível na loja', verbose_name='Ativo')),
                ('imagem_url', models.URLField(blank=True, help_text='URL da imagem do produto', null=True, verbose_name='URL da Imagem')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['-data_criacao'],
                'indexes': [models.Index(fields=['categoria'], name='api_product_categor_b620e7_idx'), models.Index(fields=['ativo'], name='api_product_ativo_57a7ef_idx'), models.Index(fields=['data_criacao'], name='api_product_data_cr_c05ffe_idx')],
            },
        ),
    ]
