# Generated by Django 5.2.4 on 2025-07-09 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_product_ativo_alter_product_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categoria',
            field=models.CharField(choices=[('Eletrônicos', 'Eletrônicos'), ('Informática', 'Informática'), ('Áudio', 'Áudio'), ('Casa e jardim', 'Casa e Jardim'), ('Esportes', 'Esportes'), ('Moda', 'Moda'), ('Livros', 'Livros')], help_text='Categoria do produto', max_length=50, verbose_name='Categoria'),
        ),
    ]
